timeplus/blog/urls.py
from django.contrib import admin
from django.urls import path,re_path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_summary, name = 'blog_summary'),
    re_path('(?P<article_id>\d)/', views.blog_article, name = 'blog_article'),
]

timeplus/timeplus/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

timeplus/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class BlogArticles(models.Model):
    title = models.CharField(max_length = 300)
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return "< {} {} {} >".format(self.title,self.author,self.publish)

timeplus/blog/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.

from . import models

def blog_summary(request):
    blogs = models.BlogArticles.objects.all()
    return render(request, 'blog/summary.html', {'blogs' : blogs})

def blog_article(request, article_id):
    article = get_object_or_404(models.BlogArticles, id=article_id)
    return render(request, 'blog/article.html', {'article' : article})

timeplus/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
        	{% block content %} {% endblock %}
        </div>

        {% include "footer.html" %}
        {% block javascript %}{% endblock %}

        <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>

    </body>
</html>

timeplus/templates/blog/article.html
{% extends "base.html" %}
{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
	<h1>{{ article.title }}</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left: 20px">{{ article.publish }}1</span></p>
		<div>{{ article.body }}</div>
	</div>
	<div class="col-xs-6 col-md-4">
		  <h2>Hexo Blog is Hosted on Github</h2>
		  <p>Location：www.oamsocool.github.io</p>
		  <img width="200px" src="http://img.52jbj.com/uploads/allimg/150623/1-1506230Z149.jpg">
	</div>
</div>
{% endblock %}

timeplus/templates/blog/summary.html
{% extends "base.html" %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
	<h1>My Blog</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<ul>
			{% for blog in blogs %}
			<li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
			{% endfor %}
		</ul>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>Hexo Blog is Hosted on Github</h2>
		<p>Location：www.oamsocool.github.io</p>
		<img width="200px" src="http://img.52jbj.com/uploads/allimg/150623/1-1506230Z149.jpg">
	</div>
</div>
{% endblock %}

timeplus/templates/footer.html
<div class="container">
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

timeplus/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
	      </div>
	      <div>
	          <ul class="nav navbar-nav" role="navigation">
		            <li><a href="{% url 'blog:blog_summary' %}">BLOG</a></li>
	          </ul>
	      </div>
    </nav>
</div>